%% Function that writes into the excel the selected structure of data
function  [Stab_der_parts_lateraldirectional name_stab_der_parts_lateraldirectional] = Write_DATA_complete_AC_sheet4(Storing_DATA,...
    M_alpha_cero,V_alpha_cero,conv_UNITS,mission_actual,n,case_AC,OUTPUT_read_XLSX,filename,Sheet_AC3,prefix)

Storing_GEO_DATA_1 = Storing_DATA.Storing_GEO_DATA_1;
Storing_WEIGHT_DATA_1 = Storing_DATA.Storing_WEIGHT_DATA_1;
Storing_AERO_DATA_1 = Storing_DATA.Storing_AERO_DATA_1;
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
% performance
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
Storing_PERFORMANCE_DATA_1 = Storing_DATA.Storing_PERFORMANCE_DATA_1;
Storing_PERFORMANCE_DATA_21 = Storing_DATA.Storing_PERFORMANCE_DATA_21;
Storing_PERFORMANCE_DATA_22 = Storing_DATA.Storing_PERFORMANCE_DATA_22;
Storing_PERFORMANCE_DATA_23 = Storing_DATA.Storing_PERFORMANCE_DATA_23;
Storing_PERFORMANCE_DATA_24 = Storing_DATA.Storing_PERFORMANCE_DATA_24;
Storing_PERFORMANCE_DATA_25 = Storing_DATA.Storing_PERFORMANCE_DATA_25;
Storing_PERFORMANCE_DATA_26 = Storing_DATA.Storing_PERFORMANCE_DATA_26;
Storing_PERFORMANCE_DATA_27 = Storing_DATA.Storing_PERFORMANCE_DATA_27;
% Stability
Storing_STABILITY_DATA_1 = Storing_DATA.Storing_STABILITY_DATA_1;
Storing_STABILITY_DATA_2 = Storing_DATA.Storing_STABILITY_DATA_2;
Storing_STABILITY_DATA_2B = Storing_DATA.Storing_STABILITY_DATA_2B;
Storing_STABILITY_DATA_3 = Storing_DATA.Storing_STABILITY_DATA_3;
Storing_STABILITY_DATA_4A = Storing_DATA.Storing_STABILITY_DATA_4A;
Storing_STABILITY_DATA_4B = Storing_DATA.Storing_STABILITY_DATA_4B;
Storing_STABILITY_DATA_4C = Storing_DATA.Storing_STABILITY_DATA_4C;
Storing_STABILITY_DATA_4D = Storing_DATA.Storing_STABILITY_DATA_4D;
Storing_STABILITY_DATA_5 = Storing_DATA.Storing_STABILITY_DATA_5;

AC_type = OUTPUT_read_XLSX.AC_Data_flags.AC_type;
 
Stab_der_parts_lateraldirectional = [Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta;... % Sideslip Force Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_nac;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_fus;...
% Sideslip Rolling Moment Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_VP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_HP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_VP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_HP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_nac;...
% Sideslip Yawing Moment Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_fus;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_nac;...
% Side Force due to roll rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_p_nac;...
% Roll Moment due to roll rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_p_nac;...
% Yaw Moment due to roll rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_p_nac;...
% Side Force due to yaw rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_r_nac;...
% Roll Moment due to yaw rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_r_nac;...
% Yaw Moment due to yaw rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_r_nac;...
% Side Force due to Side slip rate
Storing_STABILITY_DATA_1.Stab_Der_parts.Cybpunto;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_betaDot_nac;...
% Roll moment due to Side slip rate
Storing_STABILITY_DATA_1.Stab_Der_parts.Clbpunto;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_betaDot_nac;...
% Yaw moment due to Side slip rate
Storing_STABILITY_DATA_1.Stab_Der_parts.Cnbpunto;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_betaDot_nac];

% Automatizes the range of cells for each data-write up
% Range for Geometry write up in Excel
initial = 1;
N_elements_aero = 123;
range_aero_i = initial + 1;
range_aero_f = initial + N_elements_aero;
RANGE_aero_i = num2str(range_aero_i);
RANGE_aero_f = num2str(range_aero_f);
st_aero_i = strcat(RANGE_aero_i);
st_aero_f = strcat(RANGE_aero_f);

% Generates the name for the range of write up cells
name_stab_der_parts_lateraldirectional   = strcat(prefix,st_aero_i,':',prefix,st_aero_f);