%% Function that writes into the excel the selected structure of data
function [Stab_der_parts_longitudinal name_stab_der_parts_longitudinal] = Write_DATA_complete_AC_sheet3(Storing_DATA,...
    M_alpha_cero,V_alpha_cero,conv_UNITS,mission_actual,n,case_AC,OUTPUT_read_XLSX,filename,Sheet_AC2,prefix)

Storing_GEO_DATA_1 = Storing_DATA.Storing_GEO_DATA_1;
Storing_WEIGHT_DATA_1 = Storing_DATA.Storing_WEIGHT_DATA_1;
Storing_AERO_DATA_1 = Storing_DATA.Storing_AERO_DATA_1;
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
% performance
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
Storing_PERFORMANCE_DATA_1 = Storing_DATA.Storing_PERFORMANCE_DATA_1;
Storing_PERFORMANCE_DATA_21 = Storing_DATA.Storing_PERFORMANCE_DATA_21;
Storing_PERFORMANCE_DATA_22 = Storing_DATA.Storing_PERFORMANCE_DATA_22;
Storing_PERFORMANCE_DATA_23 = Storing_DATA.Storing_PERFORMANCE_DATA_23;
Storing_PERFORMANCE_DATA_24 = Storing_DATA.Storing_PERFORMANCE_DATA_24;
Storing_PERFORMANCE_DATA_25 = Storing_DATA.Storing_PERFORMANCE_DATA_25;
Storing_PERFORMANCE_DATA_26 = Storing_DATA.Storing_PERFORMANCE_DATA_26;
Storing_PERFORMANCE_DATA_27 = Storing_DATA.Storing_PERFORMANCE_DATA_27;
% Stability
Storing_STABILITY_DATA_1 = Storing_DATA.Storing_STABILITY_DATA_1;
Storing_STABILITY_DATA_2 = Storing_DATA.Storing_STABILITY_DATA_2;
Storing_STABILITY_DATA_2B = Storing_DATA.Storing_STABILITY_DATA_2B;
Storing_STABILITY_DATA_3 = Storing_DATA.Storing_STABILITY_DATA_3;
Storing_STABILITY_DATA_4A = Storing_DATA.Storing_STABILITY_DATA_4A;
Storing_STABILITY_DATA_4B = Storing_DATA.Storing_STABILITY_DATA_4B;
Storing_STABILITY_DATA_4C = Storing_DATA.Storing_STABILITY_DATA_4C;
Storing_STABILITY_DATA_4D = Storing_DATA.Storing_STABILITY_DATA_4D;
Storing_STABILITY_DATA_5 = Storing_DATA.Storing_STABILITY_DATA_5;

AC_type = OUTPUT_read_XLSX.AC_Data_flags.AC_type;
 
Stab_der_parts_longitudinal = ...
    [Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_w1_e_corrected;... % CL0
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_can_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_HTP_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_vee_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_vee2_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_VTP_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_Nac_e_corrected;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_fus;...
% CLalpha
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_w1_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_can_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_HTP_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_vee_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_vee2_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_VTP_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CLalpha_Nac_e_pw;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alpha_fus;...
% TOTAL CM0
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_0_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_0_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_0_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_0_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_0_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_fus;...
% CM0 corrected/normalized withn dynamic pressure and Surface area
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_w1_ae;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_can_ae;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_HTP_ae;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_vee_ae;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_vee2_ae;...
% CM0 cincludidn the contribution of the CL0 lift
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_w1_CL0;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_can_CL0;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_HTP_CL0;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_vee_CL0;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM0_vee2_CL0;...
% Total Aircraft 
Storing_STABILITY_DATA_1.Stab_Der_parts.CL0_ac;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alpha_ac;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alpha_ac;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alpha_fus;...
% Lift Pitch Rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_fus;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_q_nac;...
% Moment Pitch Rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_fus;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_q_nac;...
% Drag Pitch Moment Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_nac;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CD_q_fus;...
% Lift Angle of Attach Rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_fus;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CL_alphapunto_nac;...
% Moment Angle of Attach Rate Derivatives
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_fus;...
Storing_STABILITY_DATA_1.Stab_Der_parts.CM_alphapunto_nac];

% Automatizes the range of cells for each data-write up
% Range for Geometry write up in Excel
initial = 1;
N_elements_aero = 76;
range_aero_i = initial + 1;
range_aero_f = initial + N_elements_aero;
RANGE_aero_i = num2str(range_aero_i);
RANGE_aero_f = num2str(range_aero_f);
st_aero_i = strcat(RANGE_aero_i);
st_aero_f = strcat(RANGE_aero_f);

% Generates the name for the range of write up cells
name_stab_der_parts_longitudinal   = strcat(prefix,st_aero_i,':',prefix,st_aero_f);

