%% Function that writes into the excel the selected structure of data
function [Aero_comparativa,name_aero_comprativa] = Write_DATA_complete_AC_sheet2(Storing_DATA,...
    M_alpha_cero,V_alpha_cero,conv_UNITS,mission_actual,n,case_AC,OUTPUT_read_XLSX,filename,Sheet_AC2,prefix)

Storing_GEO_DATA_1 = Storing_DATA.Storing_GEO_DATA_1;
Storing_WEIGHT_DATA_1 = Storing_DATA.Storing_WEIGHT_DATA_1;
Storing_AERO_DATA_1 = Storing_DATA.Storing_AERO_DATA_1;
% performance
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
Storing_PERFORMANCE_DATA_1 = Storing_DATA.Storing_PERFORMANCE_DATA_1;
Storing_PERFORMANCE_DATA_21 = Storing_DATA.Storing_PERFORMANCE_DATA_21;
Storing_PERFORMANCE_DATA_22 = Storing_DATA.Storing_PERFORMANCE_DATA_22;
Storing_PERFORMANCE_DATA_23 = Storing_DATA.Storing_PERFORMANCE_DATA_23;
Storing_PERFORMANCE_DATA_24 = Storing_DATA.Storing_PERFORMANCE_DATA_24;
Storing_PERFORMANCE_DATA_25 = Storing_DATA.Storing_PERFORMANCE_DATA_25;
Storing_PERFORMANCE_DATA_26 = Storing_DATA.Storing_PERFORMANCE_DATA_26;
Storing_PERFORMANCE_DATA_27 = Storing_DATA.Storing_PERFORMANCE_DATA_27;
% Stability
Storing_STABILITY_DATA_1 = Storing_DATA.Storing_STABILITY_DATA_1;
Storing_STABILITY_DATA_2 = Storing_DATA.Storing_STABILITY_DATA_2;
Storing_STABILITY_DATA_2B = Storing_DATA.Storing_STABILITY_DATA_2B;
Storing_STABILITY_DATA_3 = Storing_DATA.Storing_STABILITY_DATA_3;
Storing_STABILITY_DATA_4A = Storing_DATA.Storing_STABILITY_DATA_4A;
Storing_STABILITY_DATA_4B = Storing_DATA.Storing_STABILITY_DATA_4B;
Storing_STABILITY_DATA_4C = Storing_DATA.Storing_STABILITY_DATA_4C;
Storing_STABILITY_DATA_4D = Storing_DATA.Storing_STABILITY_DATA_4D;
Storing_STABILITY_DATA_5 = Storing_DATA.Storing_STABILITY_DATA_5;

AC_type = OUTPUT_read_XLSX.AC_Data_flags.AC_type;
 
Aero_comparativa = [%% WING
Storing_AERO_DATA_1.Aero.CL_0_w1_CR;...
Storing_AERO_DATA_1.Aero.CL_alpha_w1_CR;...
Storing_AERO_DATA_1.Aero.CM_0_w1_CR;...
Storing_AERO_DATA_1.Aero.CL_max_w1_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_w1_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_w1_ope;...
Storing_AERO_DATA_1.Aero.CL_w1_CR_ope;...
Storing_AERO_DATA_1.Aero.E_w1_max_R_jet;...
Storing_AERO_DATA_1.Aero.E_w1_max_E_jet;...
Storing_AERO_DATA_1.Aero.E_w1_max_E_prop;...
%% CAN
Storing_AERO_DATA_1.Aero.CL_0_can_CR;...
Storing_AERO_DATA_1.Aero.CL_alpha_can_CR;...
Storing_AERO_DATA_1.Aero.CM_0_can_CR;...
Storing_AERO_DATA_1.Aero.CL_max_can_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_can_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_can_ope;...
Storing_AERO_DATA_1.Aero.CL_can_CR_ope;...
Storing_AERO_DATA_1.Aero.E_can_max_E_prop;...
Storing_AERO_DATA_1.Aero.E_can_max_R_jet;...
Storing_AERO_DATA_1.Aero.E_can_max_E_jet;...
%% HTP
Storing_AERO_DATA_1.Aero.CL_0_HTP_CR;...
Storing_AERO_DATA_1.Aero.CL_alpha_HTP_CR;...
Storing_AERO_DATA_1.Aero.CM_0_HTP_CR;...
Storing_AERO_DATA_1.Aero.CL_max_HTP_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_HTP_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_HTP_ope;...
Storing_AERO_DATA_1.Aero.CL_HTP_CR_ope;...
Storing_AERO_DATA_1.Aero.E_HTP_max_E_prop;...
Storing_AERO_DATA_1.Aero.E_HTP_max_R_jet;...
Storing_AERO_DATA_1.Aero.E_HTP_max_E_jet;...
%% Vee
Storing_AERO_DATA_1.Aero.CL_0_vee_CR;...
Storing_AERO_DATA_1.Aero.CL_alpha_vee_CR;...
Storing_AERO_DATA_1.Aero.CM_0_vee_CR;...
Storing_AERO_DATA_1.Aero.CL_max_vee_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_vee_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_vee_ope;...
Storing_AERO_DATA_1.Aero.CL_vee_CR_ope;...
Storing_AERO_DATA_1.Aero.E_vee_max_E_prop;...
Storing_AERO_DATA_1.Aero.E_vee_max_R_jet;...
Storing_AERO_DATA_1.Aero.E_vee_max_E_jet;...
%% Vee2
Storing_AERO_DATA_1.Aero.CL_0_vee2_CR;...
Storing_AERO_DATA_1.Aero.CL_alpha_vee2_CR;...
Storing_AERO_DATA_1.Aero.CM_0_vee2_CR;...
Storing_AERO_DATA_1.Aero.CL_max_vee2_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_vee2_CR;...
Storing_AERO_DATA_1.Aero.alpha_max_vee2_ope;...
Storing_AERO_DATA_1.Aero.CL_vee2_CR_ope;...
Storing_AERO_DATA_1.Aero.E_vee2_max_E_prop;...
Storing_AERO_DATA_1.Aero.E_vee2_max_R_jet;...
Storing_AERO_DATA_1.Aero.E_vee2_max_E_jet;...
% Lateral
Storing_AERO_DATA_1.Aero.CYbeta_w1;...
Storing_AERO_DATA_1.Aero.Clbeta_w1;...
Storing_AERO_DATA_1.Aero.Cnbeta_w1;...
Storing_AERO_DATA_1.Aero.CYbeta_can;...
Storing_AERO_DATA_1.Aero.Clbeta_can;...
Storing_AERO_DATA_1.Aero.Cnbeta_can;...
Storing_AERO_DATA_1.Aero.CYbeta_HTP;...
Storing_AERO_DATA_1.Aero.Clbeta_HTP;...
Storing_AERO_DATA_1.Aero.Cnbeta_HTP;...
Storing_AERO_DATA_1.Aero.CYbeta_VTP;...
Storing_AERO_DATA_1.Aero.Clbeta_VTP;...
Storing_AERO_DATA_1.Aero.Cnbeta_VTP;...
Storing_AERO_DATA_1.Aero.CYbeta_vee;...
Storing_AERO_DATA_1.Aero.Clbeta_vee;...
Storing_AERO_DATA_1.Aero.Cnbeta_vee;...
Storing_AERO_DATA_1.Aero.CYbeta_vee2;...
Storing_AERO_DATA_1.Aero.Clbeta_vee2;...
Storing_AERO_DATA_1.Aero.Cnbeta_vee2;...
% Lateral Directional Derivatives
% Wing Contribution
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_w1_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_wf_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_w1;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_can_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_can_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_can;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_HTP_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_HTP_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_HTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_VTP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_VP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_HP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_vee;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cy_beta_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_VP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_HP;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_CL;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_dihedral;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cl_beta_vee2_z;...
Storing_STABILITY_DATA_1.Stab_Der_parts.Cn_beta_vee2];

% Automatizes the range of cells for each data-write up
% Range for Geometry write up in Excel
initial = 1;
N_elements_aero = 111;
range_aero_i = initial + 1;
range_aero_f = initial + N_elements_aero;
RANGE_aero_i = num2str(range_aero_i);
RANGE_aero_f = num2str(range_aero_f);
st_aero_i = strcat(RANGE_aero_i);
st_aero_f = strcat(RANGE_aero_f);

% Generates the name for the range of write up cells
name_aero_comprativa   = strcat(prefix,st_aero_i,':',prefix,st_aero_f);

