%% Function that writes into the excel the selected structure of data
function  [data_STUDY_dyn_DIMENSION name_stab_der_parts_DIMENSION] = Write_DATA_complete_AC_sheet5(Storing_DATA,...
    M_alpha_cero,V_alpha_cero,conv_UNITS,mission_actual,n,case_AC,OUTPUT_read_XLSX,filename,Sheet_AC3,prefix)

Storing_GEO_DATA_1 = Storing_DATA.Storing_GEO_DATA_1;
Storing_WEIGHT_DATA_1 = Storing_DATA.Storing_WEIGHT_DATA_1;
Storing_AERO_DATA_1 = Storing_DATA.Storing_AERO_DATA_1;
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
% performance
Storing_PROPULSION_DATA_1 = Storing_DATA.Storing_PROPULSION_DATA_1;
Storing_PERFORMANCE_DATA_1 = Storing_DATA.Storing_PERFORMANCE_DATA_1;
Storing_PERFORMANCE_DATA_21 = Storing_DATA.Storing_PERFORMANCE_DATA_21;
Storing_PERFORMANCE_DATA_22 = Storing_DATA.Storing_PERFORMANCE_DATA_22;
Storing_PERFORMANCE_DATA_23 = Storing_DATA.Storing_PERFORMANCE_DATA_23;
Storing_PERFORMANCE_DATA_24 = Storing_DATA.Storing_PERFORMANCE_DATA_24;
Storing_PERFORMANCE_DATA_25 = Storing_DATA.Storing_PERFORMANCE_DATA_25;
Storing_PERFORMANCE_DATA_26 = Storing_DATA.Storing_PERFORMANCE_DATA_26;
Storing_PERFORMANCE_DATA_27 = Storing_DATA.Storing_PERFORMANCE_DATA_27;
% Stability
Storing_STABILITY_DATA_1 = Storing_DATA.Storing_STABILITY_DATA_1;
Storing_STABILITY_DATA_2 = Storing_DATA.Storing_STABILITY_DATA_2;
Storing_STABILITY_DATA_2B = Storing_DATA.Storing_STABILITY_DATA_2B;
Storing_STABILITY_DATA_3 = Storing_DATA.Storing_STABILITY_DATA_3;
Storing_STABILITY_DATA_4A = Storing_DATA.Storing_STABILITY_DATA_4A;
Storing_STABILITY_DATA_4B = Storing_DATA.Storing_STABILITY_DATA_4B;
Storing_STABILITY_DATA_4C = Storing_DATA.Storing_STABILITY_DATA_4C;
Storing_STABILITY_DATA_4D = Storing_DATA.Storing_STABILITY_DATA_4D;
Storing_STABILITY_DATA_5 = Storing_DATA.Storing_STABILITY_DATA_5;

AC_type = OUTPUT_read_XLSX.AC_Data_flags.AC_type;
 

N1 = 35; % Número de elementos
% Selects the variable to be stotred depending if study is conducted
if  OUTPUT_read_XLSX.STUDY_flags.STABILITY_STUDY_Long_dyn == 1
    data_STUDY_Long_dyn_DIMENSION = [Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xu;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xtu;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xa;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xq;...
        % Z derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zu;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Za;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.ZaDot;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zq;...
        % M derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mu;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mtu;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Ma;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.MaDot;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mta;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mq;...
        % delta_e derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdeltae;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdeltae;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdeltae;...
        % delta_elevon derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_elevon;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_elevon;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_elevon;...
        % delta_can derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_can;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_can;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_can;...
        % delta_ruddervator derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_rv;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_rv;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_rv;...
        % delta_ruddervator2 derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_rv2;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_rv2;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_rv2
        % delta_elevator TAB derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_e_Tab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_e_Tab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_e_Tab;...
        % delta_Spoiler TAB derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Xdelta_sp;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Zdelta_sp;...
        Storing_STABILITY_DATA_1.Stab_Dyn_Long.long.Mdelta_sp];
else
    valor_constante = 0; % Valor constante
    data_STUDY_Long_dyn_DIMENSION = ones(N,1)*valor_constante;
end

N2 = 28; % Número de elementos
if OUTPUT_read_XLSX.STUDY_flags.STABILITY_STUDY_LatDir_dyn == 1
    data_STUDY_LatDir_dyn_DIMENSION = [ Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ybeta;... % Sideforce Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Yp;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Yr;...
        % Roll Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Lbeta;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Lp;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Lr;...
        % Yaw Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ntbeta;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Np;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Nr;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Nbeta;...
        % delta_a Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Yda;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Lda;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Nda;...
        % delta_rudder Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ydr;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ldr;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ndr;...
        % delta_ruddervator Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ydrv;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ldrv;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ndrv;...
        % delta_ruddervator2 Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ydrv2;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ldrv2;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ndrv2;...
        % delta_aileron TAB Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ydr_aTab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ldr_aTab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ndr_aTab;...
        % delta_rudder TAB Derivatives
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ydr_rTab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ldr_rTab;...
        Storing_STABILITY_DATA_1.Stab_Dyn_LatDir.Ndr_rTab];
else

    valor_constante = 0; % Valor constante
    data_STUDY_LatDir_dyn_DIMENSION = ones(N2,1)*valor_constante;
end


data_STUDY_dyn_DIMENSION = [data_STUDY_Long_dyn_DIMENSION;data_STUDY_LatDir_dyn_DIMENSION];

% Automatizes the range of cells for each data-write up
% Range for Geometry write up in Excel
initial = 1;
N_elements_aero = N1 + N2;
range_aero_i = initial + 1;
range_aero_f = initial + N_elements_aero;
RANGE_aero_i = num2str(range_aero_i);
RANGE_aero_f = num2str(range_aero_f);
st_aero_i = strcat(RANGE_aero_i);
st_aero_f = strcat(RANGE_aero_f);

% Generates the name for the range of write up cells
name_stab_der_parts_DIMENSION   = strcat(prefix,st_aero_i,':',prefix,st_aero_f);