function [filenameS Sheet_AC_var] = selection_filename_location(case_AC)

switch case_AC
    case 1 % case_AC = 1 - EMERGENTIA 1:1
        filename = 'Results\01_EMERGENTIA\';
        filenameb = 'Results_AC1.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 2 % case_AC = 2 - EMERGENTIA 1:2
        filename = 'Results\01_EMERGENTIA\';
        filenameb = 'Results_AC2.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 3 % case_AC = 3 - PEPIÑO XXL
        filename = 'Results\03_PEPINO\';
        filenameb = 'Results_AC3.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 4 % case_AC = 4 - A400
        filename = 'Results\04_A400\';
        filenameb = 'Results_AC4.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 5 % case_AC = 5 - MISC
        filename = 'Results\05_MISC\';
        filenameb = 'Results_AC5.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 6 % case_AC = 6 - MILVUS
        filename = 'Results\06_MILVUS\';
        filenameb = 'Results_AC6.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 7 % Existing Aircraft = 7
        filename = 'Results\05_MISC\';
        filenameb = 'Results_AC7.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 8 % case_AC = 8 - TAMIZ
        filename = 'Results\08_E26TAMIZ\';
        filenameb = 'Results_AC8.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 9 % case_AC = 9 - EMERGENTIA Wind Tunnel Model - w2
        filename = 'Results\01_EMERGENTIA\';
        filenameb = 'Results_AC9.xlsx';
        filenamec = 'Figs';
        filenamec = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 10 % case_AC = 10 - EMERGENTIA Wind Tunnel Model - w1 (sweep)
        filename = 'Results\01_EMERGENTIA\';
        filenameb = 'Results_AC10.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 11 % case_AC = 11 - EMERGENTIA Manufacturing
        filename = 'Results\11_EMERGENTIA_Manufactured\';
        filenameb = 'Results_AC11.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 12 % case_AC = 12 - ALO
        filename = 'Results\12_ALO\';
        filenameb = 'Results_AC12.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 13 % case_AC = 13 - ALO Fuel Cell
        filename = 'Results\13_ALO_Fuel_Cell\';
        filenameb = 'Results_AC13.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 14 % case_AC = 14 - A320
        filename = 'Results\14_ONEiRE\';
        filenameb = 'Results_AC14.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 15 % case_AC = 15 - EMERGENTIA Tandem Wing
        filename = 'Results\15_EMERGENTIA_v2\';
        filenameb = 'Results_AC15.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 16 % case_AC = 16 - Tarsis T75
        filename = 'Results\16_TARSIS_75\';
        filenameb = 'Results_AC16.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 17 % case_AC = 17 - Tarsis T120
        filename = 'Results\17_TARSIS_120\';
        filenameb = 'Results_AC17.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 18 % case_AC = 18 - BAT
        filename = 'Results\18_BAT\';
        filenameb = 'Results_AC18.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 19 % case_AC = 19 - FALCON2000
        filename = 'Results\19_FALCON2000\';
        filenameb = 'Results_AC19.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 20 % case_AC = 20 - SOLAR TII
        filename = 'Results\20_SOLARTII\';
        filenameb = 'Results_AC20.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 21 % case_AC = 21 - VANTUS 24
        filename = 'Results\21_VANTUS\';
        filenameb = 'Results_AC21.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 22 % case_AC = 22 - Cessna 208
        filename = 'Results\22_Cessna208\';
        filenameb = 'Results_AC22.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 23 % case_AC = 23 - King Air 350i
        filename = 'Results\23_KingAir350\';
        filenameb = 'Results_AC23.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 24 % case_AC = 24 - Future 1
        filename = 'Results\24_MK84\';
        filenameb = 'Results_AC24.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 25 % case_AC = 25 - Future 2
        filename = 'Results\25_MK84B\';
        filenameb = 'Results_AC25.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 26 % case_AC = 26 - Future 3
        filename = 'Results\26_HA\';
        filenameb = 'Results_AC26.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 27 % case_AC = 27 - Future 4
        filename = 'Results\27_FR\';
        filenameb = 'Results_AC27.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 28 % case_AC = 28 - Future 5
        filename = 'Results\28_H2\';
        filenameb = 'Results_AC28.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 29 % case_AC = 29 - Future 6
        filename = 'Results\29_Future6\';
        filenameb = 'Results_AC29.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
    case 30 % case_AC = 30 - Future 7
        filename = 'Results\30_Future7\';
        filenameb = 'Results_AC30.xlsx';
        filenamec = 'Figs';
        filenamed = 'DATA';
        filenameB = strcat(filename,filenameb);
        filename_Plots = strcat(filename,filenamec);
        filename_DATA = strcat(filename,filenamed);
end

OUTPUT_read_XLSX.PLOT_flags.fname = filename_Plots;

Sheet_AC1 = 'Results';
Sheet_AC2 = 'Comparativas';
Sheet_AC3 = 'Stab_der_Parts2';
Sheet_AC4 = 'Stab_der_Parts3';
Sheet_AC5 = 'Dim_Stab_Der1';

% Stores the names of sheets in Excel
Sheet_AC_var.Sheet_AC1 = Sheet_AC1;
Sheet_AC_var.Sheet_AC2 = Sheet_AC2;
Sheet_AC_var.Sheet_AC3 = Sheet_AC3;
Sheet_AC_var.Sheet_AC4 = Sheet_AC4;
Sheet_AC_var.Sheet_AC5 = Sheet_AC5;

% Stores the names of folders zand address
filenameS.filename = filename;
filenameS.filenameb = filenameb;
filenameS.filenamec = filenamec;
filenameS.filenamed = filenamed;
filenameS.filenameB = filenameB;
filenameS.filename_Plots = filename_Plots;
filenameS.filename_DATA = filename_DATA;


